use global vs window for SSR
if using on SSR you get this error:

```
ReferenceError: window is not defined
```

because there is no `window` in Node.js. `global` will work everywhere